DROP TABLE IF EXISTS
	`#__digistore_cart`
	,`#__digistore_cartfields`
	,`#__digistore_categories`
	,`#__digistore_currencies`
	,`#__digistore_currency_symbols`
	,`#__digistore_customers`
	,`#__digistore_customfields`
	,`#__digistore_emailreminders`
	,`#__digistore_featuredproducts`
	,`#__digistore_field_types`
	,`#__digistore_fields`
	,`#__digistore_fieldsets`
	,`#__digistore_languages`
	,`#__digistore_licensefields`
	,`#__digistore_licenseprodfields`
	,`#__digistore_licenses`
	,`#__digistore_licenses_notes`
	,`#__digistore_licenses_payments`
	,`#__digistore_logs`
	,`#__digistore_mailtemplates`
	,`#__digistore_orders`
	,`#__digistore_plans`
	,`#__digistore_prodfields`
	,`#__digistore_product_categories`
	,`#__digistore_product_groups`
	,`#__digistore_product_groups_exp`
	,`#__digistore_productclass`
	,`#__digistore_products`
	,`#__digistore_products_emailreminders`
	,`#__digistore_products_images`
	,`#__digistore_products_plans`
	,`#__digistore_products_renewals`
	,`#__digistore_promocodes`
	,`#__digistore_promocodes_orders`
	,`#__digistore_promocodes_products`
	,`#__digistore_sendmails`
	,`#__digistore_session`
	,`#__digistore_settings`
	,`#__digistore_states`
	,`#__digistore_tax_customerclass`
	,`#__digistore_tax_productclass`
	,`#__digistore_tax_rate`
	,`#__digistore_tax_rule`
	,`#__digistore_taxplugin`
	,`#__digistore_topleveldomains`;